flowchart TD
    A([Начало интервью]) --> B[ИИ проговаривает вступление по заданному шаблону]
    B --> C[Подтягивание информации о контексте собеса]
    C --> D{Решение об изменении плана собеса}
    
    D -->|Изменение плана| E[ООбновление таймлайна и плана с учетом нового или удаленного этапа]
    D -->|Продолжение работы с тем же планом| F{Определение следующего этапа в соответствии с планом}
    
    E --> F
    
    F -->|Завершение собеседования| G[Запанировано завершаем собеседование, помечая это на таймлайне]
    F -->|Продолжение собеседования| H[Генерация и озвучивание вопроса]
    
    G --> I[ИИ проговаривает прощание по заданному шаблону]
    I --> J([Конец интервью])
    
    H --> K{Ожидание ответа пользователя}
    
    K -->|Была распознана речь или речи не было| L[Анализ ответа данного в разрешенный промежуток времени и скоринг по установленной шкале]
    K -->|В течении всего времени ответа не было распознано ничего, и это не техническая неполадка| M[Вопрос пропускается и оценивается в 0 баллов]
    
    L --> N[Обновление таймплайна и сохранение результатов в контекст]
    M --> N
    
    N --> D
    
    style A fill:#90EE90,color:#006400
    style J fill:#90EE90,color:#006400
    style D fill:#FFD700,color:#000000
    style F fill:#FFD700,color:#000000
    style K fill:#FFD700,color:#000000
